name = "Fite2dmt"
uuid = "7622f6ca-2957-43dc-a3ab-f265e94f76f4"
authors = ["Dieno Diba"]
version = "1.0.0"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
KLU = "ef3ab10e-7fda-4108-b977-705223b18434"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearInterpolations = "b20c7882-2490-4592-a606-fbbfe9e745e8"
MKL = "33e6dc65-8f57-5167-99aa-e5a354878fb2"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "^1.6.7"
DelimitedFiles = "^1.9.0"
KLU = "^0.6.0"
LinearInterpolations = "^0.1.6"
MKL = "^0.7.0"
StaticArrays = "^1.9.7"
Statistics = "^1.11.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
